# AppVeyor is Continuous Integration service for Windows developers to securely build and test code

image: Visual Studio 2019

platform:
  - x86
  - x64

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38-x64"
    - PYTHON: "C:\\Python39-x64"
    - PYTHON: "C:\\Python310-x64"

matrix:
  exclude:
    - PYTHON: "C:\\Python37-x64"
      platform: x86
    - PYTHON: "C:\\Python38-x64"
      platform: x86
    - PYTHON: "C:\\Python39-x64"
      platform: x86
    - PYTHON: "C:\\Pytho310-x64"
      platform: x86
install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"  

build: false

test_script:
  - "%PYTHON%/Scripts/pytest epyt"
